### ISSUE TITLE
Adjust color for attribute values in HTML

### ISSUE THREAD

**Issue by carlcs** [gt-rios/firefox-syntax#1]
To be consistent with the dev tools, could you adjust the font color for attribute values in HTML to violett #B98EFF?

**Comment by gt-rios** [comment]
I don't know how I missed that. Thanks for letting me know, I'll fix it asap.

**Comment by gt-rios** [comment]
Hi @carlcs, I checked and it's true that the color is not consistent with the DevTools *Inspector*, but the references I'm using for the themes are the DevTools *Debugger* (for HTML and JS) and the DevTools *Style Editor* (for CSS), both are highlighted using CodeMirror if I'm not mistaken and I found them to be more uniform, which is why I use those styles.

However, If you or anyone else wants the Default Dark theme to resemble the Inspector I'll leave this snippet so you can add it to your Atom `styles.less` file:

``` less
.syntax--comment{&.syntax--html,&.syntax--xml{color:#86DE74;}} // Green html and xml comments
.syntax--string{&.syntax--html,&.syntax--xml{color: #B98EFF;}} // Violet html and xml attribute values
.syntax--punctuation.syntax--definition.syntax--tag{color: inherit;} // Text color for angle brackets in tags
.syntax--punctuation.syntax--definition.syntax--string{&.syntax--html,&.syntax--xml{color: #D7D7DB;}} // White quoted html and xml attribute values
```

Here's a comparison of the original (left) and with the snippet (right):

![screenshot](https://user-images.githubusercontent.com/17343833/33097501-691c549a-ced8-11e7-94d6-4e461f975d38.png)

I hope this helps.
